/**
 * SelfSource — writable sensory channel.
 *
 * The model writes to this channel via the `write_self` tool.
 * Content is stored in session state and injected as-is (then grid-enforced).
 * This is the model's etch-a-sketch: persistent self-portrait, orientation
 * notes, open threads. It is never auto-generated by the runtime.
 * Survives restarts via session persistence.
 */

import type { SensorySource } from "./sensory-memory.js";

export class SelfSource implements SensorySource {
  private content: string = "";

  /** Replace the entire self channel content. */
  setContent(content: string): void {
    this.content = content;
  }

  /** Get the current self channel content (for persistence). */
  getContent(): string {
    return this.content;
  }

  async poll(): Promise<string | null> {
    return this.content || null;
  }

  destroy(): void {}
}
